ALTER TABLE "works"
ADD COLUMN IF NOT EXISTS "supervisorReviewScore" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "externalReviewScore" DOUBLE PRECISION;

ALTER TABLE "reviews"
ADD COLUMN IF NOT EXISTS "isSupervisorReview" BOOLEAN NOT NULL DEFAULT false;
